Repository CapstoneAOZTG/greengrim-server, pull requests merged in 2023-11, with the labels that each got.

#40 홈화면 챌린지 조회 API & 챌린지 인증하기 API
  green/src/main/java/com/greengrim/green/core/certification/controller/RegisterCertificationController.java
  green/src/main/java/com/greengrim/green/core/certification/dto/CertificationRequestDto.java
  green/src/main/java/com/greengrim/green/core/certification/dto/CertificationResponseDto.java
  green/src/main/java/com/greengrim/green/core/certification/repository/CertificationRepository.java
  green/src/main/java/com/greengrim/green/core/certification/service/RegisterCertificationService.java
  green/src/main/java/com/greengrim/green/core/challenge/controller/GetChallengeController.java
  green/src/main/java/com/greengrim/green/core/challenge/dto/ChallengeResponseDto.java
  green/src/main/java/com/greengrim/green/core/challenge/repository/ChallengeRepository.java
  green/src/main/java/com/greengrim/green/core/challenge/service/GetChallengeService.java
Labels: 🐣 feature

#41 챌린지 목록 조회 API 페이징 수정
  green/src/main/java/com/greengrim/green/common/entity/SortOption.java
  green/src/main/java/com/greengrim/green/core/challenge/controller/GetChallengeController.java
  green/src/main/java/com/greengrim/green/core/challenge/service/GetChallengeService.java
Labels: 🐛 bug

#42 챌린지 페이징 수정
  green/src/main/java/com/greengrim/green/core/challenge/repository/ChallengeRepository.java
  green/src/main/java/com/greengrim/green/core/challenge/service/GetChallengeService.java
Labels: 🐛 bug

#45 인증 관련 API
  green/src/main/java/com/greengrim/green/common/exception/errorCode/CertificationErrorCode.java
  green/src/main/java/com/greengrim/green/core/certification/controller/GetCertificationController.java
  green/src/main/java/com/greengrim/green/core/certification/controller/RegisterCertificationController.java
  green/src/main/java/com/greengrim/green/core/certification/controller/UpdateCertificationController.java
  green/src/main/java/com/greengrim/green/core/certification/dto/CertificationResponseDto.java
  green/src/main/java/com/greengrim/green/core/certification/repository/CertificationRepository.java
  green/src/main/java/com/greengrim/green/core/certification/service/GetCertificationService.java
  green/src/main/java/com/greengrim/green/core/certification/service/RegisterCertificationService.java
  green/src/main/java/com/greengrim/green/core/certification/service/UpdateCertificationService.java
  green/src/main/java/com/greengrim/green/core/challenge/Category.java
  green/src/main/java/com/greengrim/green/core/challenge/controller/GetChallengeController.java
  green/src/main/java/com/greengrim/green/core/challenge/dto/ChallengeResponseDto.java
  green/src/main/java/com/greengrim/green/core/challenge/service/GetChallengeService.java
  green/src/main/java/com/greengrim/green/core/chatroom/Chatroom.java
  green/src/main/java/com/greengrim/green/core/member/Member.java
  green/src/main/java/com/greengrim/green/core/member/controller/GetMemberController.java
  green/src/main/java/com/greengrim/green/core/member/dto/MemberResponseDto.java
  green/src/main/java/com/greengrim/green/core/member/service/GetMemberService.java
  green/src/main/java/com/greengrim/green/core/member/service/RegisterMemberService.java
  green/src/main/java/com/greengrim/green/core/member/usecase/GetMemberUseCase.java
  green/src/main/java/com/greengrim/green/core/verification/VerificationController.java
  green/src/main/java/com/greengrim/green/core/verification/VerificationRepository.java
  green/src/main/java/com/greengrim/green/core/verification/VerificationService.java
Labels: 🐣 feature

#47 상호 검증 관련 API
  green/src/main/java/com/greengrim/green/common/config/EmbeddedRedisConfig.java
  green/src/main/java/com/greengrim/green/common/exception/errorCode/AuthErrorCode.java
  green/src/main/java/com/greengrim/green/core/certification/Certification.java
  green/src/main/java/com/greengrim/green/core/certification/VerificationFlag.java
  green/src/main/java/com/greengrim/green/core/certification/controller/GetCertificationController.java
  green/src/main/java/com/greengrim/green/core/certification/controller/RegisterCertificationController.java
  green/src/main/java/com/greengrim/green/core/certification/controller/UpdateCertificationController.java
  green/src/main/java/com/greengrim/green/core/certification/dto/CertificationResponseDto.java
  green/src/main/java/com/greengrim/green/core/certification/service/GetCertificationService.java
  green/src/main/java/com/greengrim/green/core/certification/service/RegisterCertificationService.java
  green/src/main/java/com/greengrim/green/core/challenge/Category.java
  green/src/main/java/com/greengrim/green/core/challenge/Challenge.java
  green/src/main/java/com/greengrim/green/core/challenge/controller/EnterChallengeController.java
  green/src/main/java/com/greengrim/green/core/challenge/controller/GetChallengeController.java
  green/src/main/java/com/greengrim/green/core/challenge/controller/RegisterChallengeController.java
  green/src/main/java/com/greengrim/green/core/challenge/service/RegisterChallengeService.java
  green/src/main/java/com/greengrim/green/core/challenge/usecase/RegisterChallengeUseCase.java
  green/src/main/java/com/greengrim/green/core/chat/controller/ChatController.java
  green/src/main/java/com/greengrim/green/core/chat/service/ChatService.java
  green/src/main/java/com/greengrim/green/core/chatroom/controller/ChatroomController.java
  green/src/main/java/com/greengrim/green/core/keyword/Keyword.java
  green/src/main/java/com/greengrim/green/core/keyword/KeywordRepository.java
  green/src/main/java/com/greengrim/green/core/keyword/KeywordService.java
  green/src/main/java/com/greengrim/green/core/member/Member.java
  green/src/main/java/com/greengrim/green/core/member/controller/GetMemberController.java
  green/src/main/java/com/greengrim/green/core/member/controller/RegisterMemberController.java
  green/src/main/java/com/greengrim/green/core/member/controller/UpdateMemberController.java
  green/src/main/java/com/greengrim/green/core/member/dto/MemberResponseDto.java
  green/src/main/java/com/greengrim/green/core/member/service/GetMemberService.java
  green/src/main/java/com/greengrim/green/core/member/service/RegisterMemberService.java
  green/src/main/java/com/greengrim/green/core/member/service/UpdateMemberService.java
  green/src/main/java/com/greengrim/green/core/member/usecase/GetMemberUseCase.java
  green/src/main/java/com/greengrim/green/core/member/usecase/RegisterMemberUseCase.java
  green/src/main/java/com/greengrim/green/core/member/usecase/UpdateMemberUseCase.java
  green/src/main/java/com/greengrim/green/core/verification/VerificationController.java
  green/src/main/java/com/greengrim/green/core/verification/VerificationRepository.java
  green/src/main/java/com/greengrim/green/core/verification/VerificationService.java
  green/src/main/java/com/greengrim/green/core/verification/dto/VerificationRequest.java
Labels: 🐣 feature, ♻️ refactor, 📜 docs

#48 Service 간 순환참조 해결
  green/src/main/java/com/greengrim/green/core/certification/service/GetCertificationService.java
  green/src/main/java/com/greengrim/green/core/verification/VerificationService.java
Labels: 🐛 bug

#49 채팅 관련 API 수정 및 추가
  green/src/main/java/com/greengrim/green/core/challenge/controller/GetChallengeController.java
  green/src/main/java/com/greengrim/green/core/challenge/dto/ChallengeResponseDto.java
  green/src/main/java/com/greengrim/green/core/challenge/repository/ChallengeRepository.java
  green/src/main/java/com/greengrim/green/core/challenge/service/GetChallengeService.java
  green/src/main/java/com/greengrim/green/core/chat/service/ChatService.java
  green/src/main/java/com/greengrim/green/core/chatparticipant/ChatparticipantRepository.java
  green/src/main/java/com/greengrim/green/core/chatparticipant/ChatparticipantService.java
Labels: 🐣 feature, ♻️ refactor

#54 출석체크 관련 API
  green/src/main/java/com/greengrim/green/common/exception/errorCode/VerificationErrorCode.java
  green/src/main/java/com/greengrim/green/core/certification/controller/GetCertificationController.java
  green/src/main/java/com/greengrim/green/core/certification/repository/CertificationRepository.java
  green/src/main/java/com/greengrim/green/core/certification/service/GetCertificationService.java
  green/src/main/java/com/greengrim/green/core/verification/VerificationService.java
Labels: 🐣 feature
