Repository CapstoneAOZTG/greengrim-server, pull requests merged in 2023-10, with the labels that each got.

#7 [Feat] Exception 처리 구현
  green/src/main/java/com/greengrim/green/common/exception/BaseException.java
  green/src/main/java/com/greengrim/green/common/exception/ControllerAdvice.java
  green/src/main/java/com/greengrim/green/common/exception/ErrorCode.java
  green/src/main/java/com/greengrim/green/common/exception/ExceptionResponse.java
  green/src/main/java/com/greengrim/green/common/exception/errorCode/GlobalErrorCode.java
Labels: 🐣 feature

#15 local db용 도커 파일 추가
  green/docker/README.md
  green/docker/database-local-m.yml
  green/docker/database-local.yml
Labels: 🏗️ infra

#24 JWT 및 Spring Security 세팅 & 회원 가입 API 구현
  green/build.gradle
  green/src/main/java/com/greengrim/green/common/auth/CurrentMember.java
  green/src/main/java/com/greengrim/green/common/auth/CustomAccessDeniedHandler.java
  green/src/main/java/com/greengrim/green/common/auth/PrincipalDetails.java
  green/src/main/java/com/greengrim/green/common/auth/PrincipalDetailsService.java
  green/src/main/java/com/greengrim/green/common/config/SecurityConfig.java
  green/src/main/java/com/greengrim/green/common/entity/BaseTime.java
  green/src/main/java/com/greengrim/green/common/exception/errorCode/AuthErrorCode.java
  green/src/main/java/com/greengrim/green/common/exception/errorCode/MemberErrorCode.java
  green/src/main/java/com/greengrim/green/common/jwt/JwtAuthenticationFilter.java
  green/src/main/java/com/greengrim/green/common/jwt/JwtExceptionFilter.java
  green/src/main/java/com/greengrim/green/common/jwt/JwtTokenProvider.java
  green/src/main/java/com/greengrim/green/core/member/Member.java
  green/src/main/java/com/greengrim/green/core/member/Role.java
  green/src/main/java/com/greengrim/green/core/member/controller/RegisterMemberController.java
  green/src/main/java/com/greengrim/green/core/member/dto/MemberRequestDto.java
  green/src/main/java/com/greengrim/green/core/member/dto/MemberResponseDto.java
  green/src/main/java/com/greengrim/green/core/member/repository/MemberRepository.java
  green/src/main/java/com/greengrim/green/core/member/service/RegisterMemberService.java
  green/src/main/java/com/greengrim/green/core/member/usecase/RegisterMemberUseCase.java
Labels: 🐣 feature

#25 JWT 종속성 추가 및 Member Entity 생성 방법 변경
  green/build.gradle
  green/src/main/java/com/greengrim/green/common/auth/PrincipalDetails.java
  green/src/main/java/com/greengrim/green/core/member/Member.java
  green/src/main/java/com/greengrim/green/core/member/service/RegisterMemberService.java
Labels: 🐛 bug

#30 로그인 API 구현
  green/src/main/java/com/greengrim/green/common/exception/errorCode/MemberErrorCode.java
  green/src/main/java/com/greengrim/green/core/member/controller/RegisterMemberController.java
  green/src/main/java/com/greengrim/green/core/member/dto/MemberRequestDto.java
  green/src/main/java/com/greengrim/green/core/member/repository/MemberRepository.java
  green/src/main/java/com/greengrim/green/core/member/service/RegisterMemberService.java
  green/src/main/java/com/greengrim/green/core/member/usecase/RegisterMemberUseCase.java
Labels: 🐣 feature

#35 로그인 및 회원 관련 API 2
  green/src/main/java/com/greengrim/green/GreenApplication.java
  green/src/main/java/com/greengrim/green/common/entity/BaseTime.java
  green/src/main/java/com/greengrim/green/common/s3/S3Service.java
  green/src/main/java/com/greengrim/green/core/member/Member.java
  green/src/main/java/com/greengrim/green/core/member/controller/GetMemberController.java
  green/src/main/java/com/greengrim/green/core/member/controller/UpdateMemberController.java
  green/src/main/java/com/greengrim/green/core/member/dto/MemberRequestDto.java
  green/src/main/java/com/greengrim/green/core/member/dto/MemberResponseDto.java
  green/src/main/java/com/greengrim/green/core/member/service/GetMemberService.java
  green/src/main/java/com/greengrim/green/core/member/service/RegisterMemberService.java
  green/src/main/java/com/greengrim/green/core/member/service/UpdateMemberService.java
  green/src/main/java/com/greengrim/green/core/member/usecase/GetMemberUseCase.java
  green/src/main/java/com/greengrim/green/core/member/usecase/UpdateMemberUseCase.java
Labels: 🐣 feature

#37 채팅- 입퇴장 이벤트, 인원 수 처리
  green/src/main/java/com/greengrim/green/common/config/RedisConfig.java
  green/src/main/java/com/greengrim/green/common/handler/StompHandler.java
  green/src/main/java/com/greengrim/green/core/chat/ChatController.java
  green/src/main/java/com/greengrim/green/core/chat/ChatService.java
  green/src/main/java/com/greengrim/green/core/chat/dto/ChatMessage.java
  green/src/main/java/com/greengrim/green/core/chatRoom/ChatRoom.java
  green/src/main/java/com/greengrim/green/core/chatRoom/ChatRoomController.java
  green/src/main/java/com/greengrim/green/core/chatRoom/ChatRoomRepository.java
Labels: 🧪 test

#38 채팅 기능 - 프로젝트 적용 테스트
  green/src/main/java/com/greengrim/green/common/config/EmbeddedRedisConfig.java
  green/src/main/java/com/greengrim/green/common/handler/StompHandler.java
  green/src/main/java/com/greengrim/green/common/redis/RedisSubscriber.java
  green/src/main/java/com/greengrim/green/core/chat/ChatController.java
  green/src/main/java/com/greengrim/green/core/chat/ChatMessage.java
  green/src/main/java/com/greengrim/green/core/chat/ChatService.java
  green/src/main/java/com/greengrim/green/core/chat/dto/ChatMessageEnterResponse.java
  green/src/main/java/com/greengrim/green/core/chatRoom/ChatRoom.java
  green/src/main/java/com/greengrim/green/core/chatRoom/ChatRoomController.java
  green/src/main/java/com/greengrim/green/core/chatRoom/ChatRoomRepository.java
Labels: ♻️ refactor, 🧪 test
